[ADD] Addon: sale_crm_auto_won
kmee/kmee-odoo-addons pull request #63
Opened 2024-10-25 19:44 UTC by Tiago370

2024-10-28 11:57 UTC, mileo commented on sale_crm_auto_won/models/sale_order.py
> +            sale.opportunity_id.action_set_won_rainbowman()
Se a oportunidade não estiver setada não da um erro?

2024-10-28 11:59 UTC, mileo requested changes
1. Favor verificar o comentário;
2. Adicionar a pasta README e completar os arquivos conforme padrão OCA: https://github.com/OCA/maintainer-tools/tree/master/template/module/readme somente os arquivos que vc julgar relevante, os outros não incluir.
3. Remover trechos do mainifest sem uso.

2024-10-28 19:53 UTC, Tiago370 commented
@mileo corrigido.

2024-10-29 12:39 UTC, mileo approved these changes

2024-10-29 12:39 UTC, merged