[ADD] Addon: account_statement_import_ofx_invert_type
kmee/kmee-odoo-addons pull request #89
Opened 2024-12-26 14:55 UTC by Tiago370

Esse módulo adiciona a funcionalidade de inverter as transações importadas por um arquivo OFX.
![image](https://github.com/user-attachments/assets/67c47c1e-b3d1-4b3d-8289-42a950a6269b)

2024-12-27 10:15 UTC, mileo requested changes
Isso precisa ser por diário e não global.

2024-12-27 12:06 UTC, Tiago370 commented
@mileo corrigido.

2024-12-30 10:40 UTC, mileo approved these changes

2024-12-31 00:26 UTC, mileo approved these changes

2024-12-31 00:26 UTC, merged